### PR TITLE
Merge pull request #1 from fcm742-01/master

### PR DESCRIPTION
**Pull request by maritza01**
Added Maritza's picture

### CODE REVIEW

**Comment by EvanMisshula** [comment]
:-( You did not add the picture

**Comment by maritza01** [comment]
maritza_acero

**Comment by maritza01** [comment]
I get this message, I can not merge to maritza branch. Please advise. Thank you.

macero@macero-laptop MINGW64 ~/documents/Maritza_Acero/gitTutorial/students/sect                                                                     01/maritza (maritza)
$ git merge upstream/maritza
merge: upstream/maritza - not something we can merge
Date: Sun, 14 Feb 2016 18:17:42 -0800

**Comment by EvanMisshula** [comment]
no file added

**Pull request closed without merging**
